= Prefácio

Este é um livro em que seu autor, meu dileto amigo professor Fernando Batalha Monteiro, aborda um tema ainda encoberto pelo véu diáfano do mistério e — por que não dizer? — até mesmo da fantasia, numa linguagem simples, escoimadas de um tecnicismo exagerado que quase sempre afasta o grande público de obras dessa natureza, mas linguagem sobretudo séria e convincente.

Na primeira parte — Elementos de Cibernética — o apelo maior é à cultura geral do leitor e à sua disposição para aceitar o debate em torno de idéias novas que dizem respeito, em última análise, ao próprio ordenamento lógico do Universo em função de possíveis propósitos teleonômicos que lhe regeriam o destino. E não poderia ser diferente: o caráter multidisciplinar da "Ciência da comunicação e do controle no animal e na máquina", decorrente da integração sistêmica de todos os campos do saber, ajusta-se melhor ao geral-universal de Platão do que ao concreto-particular de Aristóteles, conforme se infere logo à leitura das primeiras páginas do livro. E é no espaço comum, assim conquistado à Lógica, à Sociologia, à Filosofia, à Biologia, à Economia, à Engenharia Industrial — citando apenas alguns segmentos da complexa tessitura do conhecimento humano — que o autor vai erigir, solidamente, os alicerces de seu bem urdido "modelo cibernético de administração industrial".

A segunda parte do livro — Cibernética Aplicada — muito embora esteja ao alcance do leitor comum, interessará mais diretamente aos profissionais das áreas de administração de empresas, economia e ciências contábeis, bem como aos docentes e discentes dessas faculdades, notadamente de disciplinas tais como: administração da produção. administração de material, custos, organização e método, organização industrial processamento de dados e outras afins. Vou mais além: concordo plenamente com o professor Batalha quando ele lamenta o atraso em que nos encontramos com relação aos países desenvolvidos, em termos de Cibernética — de quase três décadas! — e postula a criação, em nossas faculdades, da cadeira de "Cibernética e Sistemas", como um esforço adicional visando à transposição do perigoso fosso tecnológico que se antepõe, como uma barreira, aos nossos mais líbidos anseios de progresso econômico e social. E o que, em sã consciência, me diz a experiência haurida durante quase toda uma existência devotada ao serviço público e ao magistério superior.

SISTEMA INTEGRADO DE PROGRAMAÇÃO E CONTROLE DA PRODUÇÃO — Um modelo cibernético de administração industrial, não é uma obra de leitura fácil, mas quem o fizer sentir-se-á, certamente, recompensado pelo tempo empregado. Os críticos do modelo, estes terão, também, com toda certeza, encontrado respostas convincentes para questões que, antes, lhes alimentavam o ceticismo quanto à viabilidade das aplicações da cibernética na administração industrial: o conceito de entropia, transposto da termodinâmica para a teoria da informação; a analogia entre o modelo neurofisiológico animal e a empresa, uma antevisão de Fayol operacionalizada pela cibernética; a falácia do robô, tema bastante atual e que suscita considerações sutis sobre autonomia, automatismo e automação; uma falácia da informática — pela primeira vez formalmente conceituada: a relação implícita no conjunto afim de variáveis INFORMAÇÃO-COMPUTADOR-SISTEMA — que trata da polêmica questão do uso e abuso dos computadores na administração industrial, e muitas outras colocações, vistas sob o novo e revolucionário enfoque da Ciência Cibernética.

Está de parabéns, pois, o professor Batalha, pelo valor inegável de sua obra, e também, de certa forma, como ele próprio faz questão de proclamar, a Universidade do Amazonas, que o teve como aluno brilhante de dois cursos de graduação — administração de empresas e Ciências Contábeis — e de um curso de pós-graduação — Contabilidade Gerencial — e onde, atualmente, completa com igual brilhantismo, o curso de Ciências Econômicas, na sua permanente ânsia de aquisição de saber.

Manaus, Abril de 1982.

Aurêlio Coutinho de Almeida.

#pagebreak()

= Prefácio do Autor

A idéia de escrever este livro nasceu no final da década de sessenta, embora de forma ainda vaga e imprecisa, ao ler "Admirável Mundo Novo", de Aldous Leonard Huxley. Qual a implicação dessa obra — um romance satírico com a cibernética, de que eu possuía então informações apenas superficiais, somente mais tarde emergiria em meu pensamento; o que foi fruto da intuição, entretanto, passou desde logo a motivar-me para a pesquisa em torno desse assunto.

A antevisão de uma sociedade ultra-estável apesar de constituída de seres humanos — imprevisíveis em seus desígnios e a partir de certo ponto ingovernáveis como entidades dotadas de discernimento e livre-arbítrio — somente seria possível sob um novo conceito de organização. O admirável mundo novo, realização da utopia pela Ciência, consiste de um mecanismo preciso e ajustado, como o de relojoaria — atente-se para o fato de que Huxley era filosoficamente mecanicista — cujos componentes, imitando o comportamento finalista dos seres vivos, interagem e se inter-relacionam sinergicamente face a propósitos teleonômicos comuns, finalidade da organização em termos de realização plena de seu projeto.

O curioso a registrar da obra de Huxley é que, ao escrevê-la, seu intento era de desagravar a Ciência, que pensava estar destruindo os valores humanos e políticos; paradoxalmente, entretanto, colocou no governo do admirável mundo novo um Estado totalitário, organizado sob a égide da Ciência, em que o discernimento e o livre-arbítrio foram completamente erradicados da mente de seus habitantes.

A idéia básica de Huxley — um mundo sistêmico, regido por leis universais que atuam de forma comum nos campos animados e inanimados, uma espécie de mecanismo biológico — teve motivação mais filosófica do que científica. Sua obra dista de 1932, e creio que Viener e Bertalanffy, que trataram da questão sob um enfoque eminentemente científico, sem desprezar, entretanto, o conteúdo filosófico que lhe é inerente, devem a Huxley a primazia da incursão nos futuros domínios da cibernética e dos sistemas.

Cibernética e Sociedade — o uso humano dos seres humanos, e Teoria Geral dos Sistemas (ver bibliografia), confirmaram a intuição nascida com a leitura do Admirável Mundo Novo e constituíram minha iniciação na cibernética. A partir daí, a idéia de escrever este livro foi tomando força à medida que chegavam ao Brasil os novos progressos da cibernética, através de autores estrangeiros traduzidos para o vernáculo. Duas particularidades reforçavam, também, dia a dia, a idéia, em fase de maturação. A primeira delas, o fato de se tratar de uma Ciência que dispensa, tanto em seu aspecto puro quanto no aplicado, o uso de materiais e equipamentos especificamente destinados à realização de experimentos e de aplicações práticas. O laboratório do ciberneta poderá ser, sem maiores restrições, seu próprio pensamento, sua imaginação criadora, alimentada, muitas vezes, pela intuição, enquanto que o campo de provas de suas inferências poderá ser desde seu ambiente de trabalho ou seu domicílio até o caminho percorrido para chegar a um ou outro lugar. O lado imaterial da questão, por sua vez, dispensa qualificações ou aptidões especiais, que poderiam até mesmo prejudicar se acompanhadas de atrofia dos demais campos do conhecimento. O caráter de universalidade de que se reveste a cibernética é condicionado pela integração de todos os campos do saber, o que implica, para seus aficionados de qualquer nível, a posse de uma razoável dose de cultura geral e pressupõe o emprego de mentes abertas para o diálogo e livres de condicionamentos ou rótulos ideológicos.

A segunda particularidade que me animou a escrever este livro diz respeito à inexistência de obra de autor brasileiro, por tal motivo atento à nossa realidade econômica e cultural, que trate da cibernética em seu conteúdo global, sem dissociá-la do contexto no qual a "Ciência da comunicação, e do controle no animal e na máquina" se insere, que é o contexto dos sistemas. Talvez seja esta a causa de não se contar, no Brasil, até hoje, com uma cadeira de "Cibernética e Sistemas" em nossas universidades. E esta é a minha modesta contribuição, na certeza de que se trata de assunto básico para os estudantes de economia, administração de empresas, ciências contábeis e engenharia industrial, na parte relativa à formulação de modelos organizacionais e de controle operacional inerentes à cibernética aplicada. Quanto aos estudantes dos cursos de currículos biológicos, a cibernética pura, que se vale em grande parte do modelo neurofisiológico para a formulação de princípios aplicáveis à comunicação e ao controle nos sistemas não-orgânicos, oferecerá campo fecundo para a pesquisa e o desenvolvimento de novas e importantes teorias.

Finalmente, justo se torna creditar à Companhia Cervejaria Brahma, pelo prêmio que instituiu, desde 1974, para incentivar a pesquisa no campo da administração de empresas, a maior parte da motivação que fez com que a idéia de escrever este livro se transformasse na ação correspondente.

Manaus, abril de 1982.

F.B.M

#pagebreak()

= Apresentação

O empresário de hoje, inserido numa realidade extremamente mutável, pois em constante evolução, tem que suportar o ônus de sua permanência em um mercado cada vez mais competitivo e exigente. Mas a moeda com que presta a satisfação desse tributo é cunhada na própria empresa e o padrão-ouro das relações de troca consiste em estratégias capazes de engendrar mecanismos de ação destinados a se antecipar às pressões que partem do contexto macroeconômico do sistema maior, na direção do sistema microeconômico no qual a empresa se integra, interage e inter-relaciona.

A cibernética — ciência da comunicação e do controle no animal e na máquina — oferece, à ciência da administração, instrumentos tendentes a otimizar a performance empresarial de forma a impelir a curva das possibilidades de produção para as proximidades do ponto de locação das satisfações humanas, única resposta cabal ao grave desafio do presente.

Dentro dessa ordem de idéias — formulação de estratégias de ação apriorístico — desenvolveu-se, neste trabalho, a metodologia a que se deu, talvez presunçosamente, o título de "SISTEMA" INTEGRADO DE PROGRAMAÇÃO E CONTROLE DE PRODUÇÃO — Um modelo cibernético de administração industrial, que visa a instituir, no organismo empresarial, um sistema físico de produção, ciberneticamente operado por um sistema de gestão administrativo de concebido.

A obra desenvolve-se em duas partes. Na primeira — ELEMENTOS DE CIBERNÉTICA — são feitas rápidas incursões nos domínios puros desta jovem ciência, visando a familiarizar o leitor com os termos e conceitos que lhe darão acesso ao novo instrumental de otimização da performance empresarial. Na segunda parte — CIBERNÉTICA APLICADA À ADMINISTRAÇÃO INDUSTRIAL — a ciência pura, teórica, terá aplicação prática na solução de um problema empresarial, típico desta era de crescimento rápido e desordenado da economia nacional: a crise de crescimento da ALPHA — Implementos Industriais SA, empresa hipoteticamente criada, mas que guarda quase total analogia com suas congêneres da vida real.

O primeiro congresso internacional de cibernética realizou-se em Estocolmo, há quase três décadas. Apesar de ser, como já dissemos, uma ciência jovem, seus efeitos práticos são, particularmente, notáveis. Infelizmente, no Brasil, a cibernética tem pouca divulgação, não fazendo parte das disciplinas curriculares de nenhum curso de administração, economia, ciências contábeis ou engenharia de nossas faculdades. Talvez, por essa razão, aliada a uma certa dose de resistência à mudança, alguns céticos das possibilidades da cibernética objetem, ao concluir a leitura desta obra, tratar-se de mais um "sonho de uma noite de verão".

A estes, respondo com as palavras do mercenário idealista de Laterguy: "há muito sonho no homem de ação, e muita ação no homem que sonha..."
