import Config

# Configure your database
config :sipcp_companion, SipcpCompanion.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "sipcp_companion_dev",
  port: String.to_integer(System.get_env("PGPORT") || "5432"),
  socket_dir: System.get_env("PGHOST"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sipcp_companion, SipcpCompanionWeb.Endpoint,
  # HTTP + HTTPS (HTTPS needed for Web Speech API)
  http: [ip: {0, 0, 0, 0}],
  https: [
    ip: {0, 0, 0, 0},
    port: 4001,
    keyfile: "priv/cert/selfsigned_key.pem",
    certfile: "priv/cert/selfsigned.pem"
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "H5Y/NwsrOVNrG+/laXMOkDed1Wusw8HTItUBO3cDdl6aa8qQQu+B5kAYMUy92Xm1",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sipcp_companion, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sipcp_companion, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :sipcp_companion, SipcpCompanionWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/sipcp_companion_web/router\.ex$",
      ~r"lib/sipcp_companion_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :sipcp_companion, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
